
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sft-web-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/dehnis-io/sft-web.git"
    targetRevision: HEAD                      # watch the latest commit
    path: sft-web-helm-chart                  # Project helm chart in the repository
    helm:
      releaseName: sft-web-project
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"   # same cluster where Argocd is running 
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true