replicaCount: 3

image:
  name: techadvocate247/sft-web
  tag: 4ca8fc7
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80
  # Add targetPort if your app uses different container port
  # targetPort: 8080

ingress:
  enabled: false

serviceAccount:
  enabled: false
  create: false
  name: ""

autoscaling:
  enabled: false

resources:
  limits:
    memory: "256Mi"
    cpu: "250m"
  requests:
    memory: "128Mi"
    cpu: "100m"

livenessProbe:
  enabled: true
  path: /
  port: 80
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

env: []
# Example:
# - name: ENV_VAR
#   value: "value"

volumeMounts: []
# Example:
# - name: config
#   mountPath: /app/config

volumes: []
# Example:
# - name: config
#   configMap:
#     name: app-config

nodeSelector: {}

tolerations: []

affinity: {}