replicaCount: 3

image:
  name: techadvocate247/sft-web
  tag: 7f3c5be
  pullPolicy: IfNotPresent

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  # Optional: add targetPort if your app uses different container port
  targetPort: 8080

ingress:
  enabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false

# Add these sections:
resources:
  limits:
    memory: "256Mi"
    cpu: "250m"
  requests:
    memory: "128Mi"
    cpu: "100m"