replicaCount: 3

image:
  name: techadvocate247/sft-web
  tag: 4ca8fc7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false
