---

name: Complete sft-website devops pipeline

on:
  push:
    branches:
      - main 

jobs: 
  build_and_push:
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout Repository
      uses: actions/checkout@v2 

    - name: Set Short SHA 
      run: | 
        echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV   
# Creates a shortened version (first 7 characters) of the Git commit SHA and sets it as an environment variable SHORT_SHA 

    - name: Build docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sft-web:${{ env.SHORT_SHA }} .

    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

# opt 2
    # - name: Login to Dockerhub
    #   run: |
    #     echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push to Docker Repository
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/sft-web:${{ env.SHORT_SHA }} 